version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    links:
      - "db:database"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: