# Generated by Django 2.2.5 on 2019-09-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'armor classes',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hit_points', models.CharField(max_length=25)),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('WIS', models.IntegerField()),
                ('CHA', models.IntegerField()),
                ('challenge', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('traits', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('legendary_actions', models.TextField(blank=True, null=True)),
                ('reactions', models.TextField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('armor_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='api.ArmorClass')),
                ('condition_immunities', models.ManyToManyField(related_name='monsters', to='api.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.Monster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='api.Monster')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sense')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSavingThrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('ability_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AbilityScore')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_throws', to='api.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterMovementSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeds', to='api.Monster')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MovementType')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterDamageVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DamageType')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='api.Monster')),
            ],
            options={
                'verbose_name_plural': 'monster damage vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='MonsterDamageResistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DamageType')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='api.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterDamageImmunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DamageType')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunities', to='api.Monster')),
            ],
            options={
                'verbose_name_plural': 'monster damage immunities',
            },
        ),
    ]
